_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 3
                - 16
                - 23
                - 55
            "4": 3.13.0
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": darwin-arm64
batch_size:
    value: 256
gamma:
    value: 0.99
lr:
    value: 0.0003
max_episodes:
    value: 1000
tau:
    value: 0.005
