# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serialprotocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14serialprotocol.proto\x12\x11inverted_pendulum\"\x1f\n\x0cRequestState\x12\x0f\n\x07message\x18\x01 \x02(\t\"\x1e\n\rResponseState\x12\r\n\x05\x61ngle\x18\x01 \x02(\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serialprotocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTSTATE._serialized_start=43
  _REQUESTSTATE._serialized_end=74
  _RESPONSESTATE._serialized_start=76
  _RESPONSESTATE._serialized_end=106
# @@protoc_insertion_point(module_scope)
