/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_INVERTED_PENDULUM_SERIALPROTOCOL_PB_H_INCLUDED
#define PB_INVERTED_PENDULUM_SERIALPROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _inverted_pendulum_RequestState {
    pb_callback_t message;
} inverted_pendulum_RequestState;

typedef struct _inverted_pendulum_ResponseState {
    double angle;
} inverted_pendulum_ResponseState;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define inverted_pendulum_RequestState_init_default {{{NULL}, NULL}}
#define inverted_pendulum_ResponseState_init_default {0}
#define inverted_pendulum_RequestState_init_zero {{{NULL}, NULL}}
#define inverted_pendulum_ResponseState_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define inverted_pendulum_RequestState_message_tag 1
#define inverted_pendulum_ResponseState_angle_tag 1

/* Struct field encoding specification for nanopb */
#define inverted_pendulum_RequestState_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   message,           1)
#define inverted_pendulum_RequestState_CALLBACK pb_default_field_callback
#define inverted_pendulum_RequestState_DEFAULT NULL

#define inverted_pendulum_ResponseState_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, DOUBLE,   angle,             1)
#define inverted_pendulum_ResponseState_CALLBACK NULL
#define inverted_pendulum_ResponseState_DEFAULT NULL

extern const pb_msgdesc_t inverted_pendulum_RequestState_msg;
extern const pb_msgdesc_t inverted_pendulum_ResponseState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define inverted_pendulum_RequestState_fields &inverted_pendulum_RequestState_msg
#define inverted_pendulum_ResponseState_fields &inverted_pendulum_ResponseState_msg

/* Maximum encoded size of messages (where known) */
/* inverted_pendulum_RequestState_size depends on runtime parameters */
#define INVERTED_PENDULUM_SERIALPROTOCOL_PB_H_MAX_SIZE inverted_pendulum_ResponseState_size
#define inverted_pendulum_ResponseState_size     9

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
